# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20171228_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='future_shipping',
            field=models.BooleanField(default=False, verbose_name='future shipping'),
        ),
    ]
