# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_productvariant_future_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='future_shipping_A',
            field=models.BooleanField(default=False, verbose_name='future shipping'),
        ),
    ]
