# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_product_future_shipping_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='future_shipping_A',
            new_name='future_shipping',
        ),
    ]
