# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_product_class_to_type'),
        ('product', '0047_auto_20180101_2232'),
    ]

    operations = [
    ]
