# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_merge_20180124_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
