# Generated by Django 2.0.2 on 2018-03-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_auto_20180124_2324'),
        ('product', '0051_auto_20180202_1106'),
    ]

    operations = [
    ]
