# Generated by Django 2.0.2 on 2018-03-03 14:44

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_merge_20180303_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.PriceField(currency='GBP', decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=django_prices.models.PriceField(blank=True, currency='GBP', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cost_price',
            field=django_prices.models.PriceField(blank=True, currency='GBP', decimal_places=2, max_digits=12, null=True),
        ),
    ]
