# Generated by Django 2.0.5 on 2018-05-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_product_taxes'),
        ('product', '0052_merge_20180303_1444'),
    ]

    operations = [
    ]
