# Generated by Django 2.0.8 on 2018-09-05 06:50

from django.db import migrations

def default_supplier():
    supplier = apps.get_model('product', 'supplier')
    default_supplier = supplier.objects.get_or_create(name='default')
    return default_supplier

def make_unique(apps, schema_editor):
    MyModel = apps.get_model('product', 'product')
    for row in MyModel.objects.all():
        row.supplier = default_supplier
        row.save(update_fields=['supplier'])

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_auto_20180905_0749'),
    ]

    operations = [
        migrations.RunPython(make_unique, reverse_code=migrations.RunPython.noop),
    ]
