# Generated by Django 2.0.8 on 2018-09-05 06:54


from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0070_auto_20180905_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Supplier'),
        ),

    ]
