# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 17:52
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_merge_20171228_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethodcountry',
            name='price',
            field=django_prices.models.PriceField(currency='GBP', decimal_places=2, max_digits=12, verbose_name='price'),
        ),
    ]
