# Generated by Django 2.0.5 on 2018-05-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_auto_20180108_0814'),
        ('shipping', '0008_merge_20171228_0424'),
    ]

    operations = [
    ]
