# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 19:56
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0010_merge_20180109_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethodcountry',
            name='price',
            field=django_prices.models.PriceField(currency='GBP', decimal_places=2, max_digits=12),
        ),
    ]
