# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0010_auto_20171113_0958'),
        ('site', '0005_auto_20170720_1300'),
    ]

    operations = [
    ]
