# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0014_sitesettings_frontpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='frontpage_text',
            field=models.TextField(blank=True),
        ),
    ]
