# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0015_auto_20180110_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cyclists',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='runners',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
