# Generated by Django 2.0.5 on 2018-05-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0014_handle_taxes'),
        ('site', '0016_auto_20180111_2200'),
    ]

    operations = [
    ]
