# Generated by Django 2.0.8 on 2018-09-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0019_sitesettings_default_weight_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cyclists',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='runners',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
