# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20171117_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='company_name',
        ),
    ]
