# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '000a_remove_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='company_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='company or organization'),
        ),
    ]
