# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20171129_1004'),
        ('cart', '0003_auto_20170720_1300'),
    ]

    operations = [
    ]
