# Generated by Django 2.0.5 on 2018-05-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_merge_20171228_0424'),
        ('cart', '0006_auto_20180221_0825'),
    ]

    operations = [
    ]
