# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20180108_0814'),
        ('cart', '0006_auto_20171228_1752'),
    ]

    operations = [
    ]
