# Generated by Django 2.0.5 on 2018-05-25 09:04

from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_merge_20180520_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('open', 'Open - currently active'), ('canceled', 'Canceled - canceled by user')], default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=django_prices.models.MoneyField(currency='GBP', decimal_places=2, default=0, max_digits=12),
        ),
    ]
