# Generated by Django 2.0.2 on 2018-03-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20180110_1956'),
        ('cart', '0006_auto_20180221_0825'),
    ]

    operations = [
    ]
