# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=30, verbose_name='Strava ID')),
                ('activity_type', models.CharField(choices=[('run', 'Run'), ('ride', 'Ride')], default='ride', max_length=4, verbose_name='Type')),
                ('distance', models.PositiveIntegerField(verbose_name='Distance')),
                ('start_date', models.DateTimeField(verbose_name='Activity Date')),
            ],
        ),
    ]
