# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0003_auto_20180106_1534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bullet',
            new_name='OldBullet',
        ),
    ]
