# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0004_auto_20180106_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email', models.EmailField(max_length=200, verbose_name='email address')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('email_checked', models.DateField(blank=True, null=True, verbose_name='date email confirmed')),
                ('email_check_ref', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='random uuid for email confirmation')),
                ('postcode', models.CharField(max_length=5, verbose_name='first part of postcode')),
                ('contact_no', models.CharField(max_length=100, verbose_name='contact number')),
                ('over_18', models.BooleanField(help_text='Please confirm that you are over 18?', verbose_name='over 18')),
                ('get_emails', models.BooleanField(help_text='Can we contact you regarding Collective events?', verbose_name='happy to receive emails')),
                ('voting_ref', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='random uuid for voting')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
