# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0004_auto_20170102_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='bullet',
            name='get_emails',
            field=models.BooleanField(help_text='Can we contact you regarding Collective events?', verbose_name='happy to receive emails'),
        ),
        migrations.AlterField(
            model_name='bullet',
            name='over_18',
            field=models.BooleanField(help_text='Please confirm that you are over 18?', verbose_name='over 18'),
        ),
    ]
