# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 12:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0005_bullet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='display_after',
            field=models.DateField(default=datetime.date.today, verbose_name='publish on'),
        ),
        migrations.AlterField(
            model_name='news',
            name='redirect_to',
            field=models.URLField(blank=True, help_text="If you put a website address in here, then don't include a story below; the news story will just redirect to this link", null=True, verbose_name='redirection story - where to go?'),
        ),
    ]
