# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0006_auto_20170115_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeloVolunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(help_text='Your address', verbose_name='address')),
                ('volunteer_type', models.CharField(choices=[('r', 'rider'), ('n', 'non-rider')], default='r', max_length=1)),
                ('entered_velo', models.BooleanField(verbose_name='have you entered the Velo?')),
                ('average_speed', models.CharField(blank=True, max_length=10, verbose_name='expected average speed for 100 mile ride')),
                ('jersey_size', models.CharField(blank=True, max_length=50, verbose_name='jersey size')),
                ('short_size', models.CharField(blank=True, max_length=50, verbose_name='bib short size')),
                ('tshirt_size', models.CharField(blank=True, max_length=50, verbose_name='t-shirt size')),
                ('bullet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bullets.Bullet')),
            ],
        ),
    ]
