# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0007_velovolunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='velovolunteer',
            name='drive_bus',
            field=models.BooleanField(default=False, verbose_name='are you willing to drive a minibus?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='velovolunteer',
            name='drive_van',
            field=models.BooleanField(default=False, verbose_name='are you willing to drive a van?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='velovolunteer',
            name='unique_ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='random uuid for emails'),
        ),
        migrations.AlterField(
            model_name='velovolunteer',
            name='average_speed',
            field=models.CharField(blank=True, max_length=10, verbose_name='expected average speed for 100mile ride (mph)'),
        ),
    ]
