# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0008_auto_20170115_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='velovolunteer',
            name='kit_sex',
            field=models.CharField(choices=[('m', 'male-fit'), ('f', 'female-fit')], default='m', max_length=1, verbose_name='do you want male or female-fit kit?'),
        ),
        migrations.AlterField(
            model_name='velovolunteer',
            name='drive_bus',
            field=models.BooleanField(help_text='Please note: By saying youu are able to drive a minibus, you are also confirming that you have a Category D1 driving licence, which means you can drive a minibus with up to 16 passenger seats without needing an additional driving test.', verbose_name='are you willing to drive a minibus?'),
        ),
        migrations.AlterField(
            model_name='velovolunteer',
            name='jersey_size',
            field=models.CharField(choices=[('xs', 'X Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'X Large'), ('xxl', 'XX Large'), ('xxxl', 'XXX Large')], max_length=4, verbose_name='jersey size'),
        ),
        migrations.AlterField(
            model_name='velovolunteer',
            name='short_size',
            field=models.CharField(choices=[('xs', 'X Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'X Large'), ('xxl', 'XX Large'), ('xxxl', 'XXX Large')], max_length=4, verbose_name='bib short size'),
        ),
        migrations.AlterField(
            model_name='velovolunteer',
            name='tshirt_size',
            field=models.CharField(choices=[('xs', 'X Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'X Large'), ('xxl', 'XX Large'), ('xxxl', 'XXX Large')], max_length=4, verbose_name='t-shirt size'),
        ),
    ]
