# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_total'),
        ('bullets', '0009_auto_20170222_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletsRunner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('address', models.TextField(help_text='Your address', verbose_name='address')),
                ('email', models.EmailField(max_length=200, verbose_name='email address')),
                ('contact_no', models.CharField(max_length=100, verbose_name='contact number')),
                ('emergency_contact_no', models.CharField(max_length=100, verbose_name='emergency contact number')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='date of birth')),
                ('club', models.CharField(blank=True, max_length=200, verbose_name='Club')),
                ('race', models.CharField(choices=[('5', '5k'), ('10', '10k')], default='5', max_length=2, verbose_name='race length')),
                ('gender', models.CharField(choices=[('f', 'female'), ('m', 'male'), ('?', 'not provided')], default='?', max_length=1, verbose_name='gender')),
                ('unique_url', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='random GUID for URLs')),
                ('order_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.AlterField(
            model_name='velovolunteer',
            name='drive_bus',
            field=models.BooleanField(verbose_name='are you willing to drive a minibus?'),
        ),
    ]
