# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0010_auto_20170404_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletsrunner',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='bulletsrunner',
            name='age',
            field=models.PositiveSmallIntegerField(default=30, help_text='Your age on the 17th September', verbose_name='age'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bulletsrunner',
            name='address',
            field=models.TextField(verbose_name='address'),
        ),
    ]
