# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-15 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0011_auto_20170404_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('story', models.TextField(verbose_name='story')),
                ('display_after', models.DateField(verbose_name='publish on')),
                ('display_until', models.DateField(blank=True, verbose_name='remove from site on')),
            ],
        ),
    ]
