# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0012_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='display_until',
            field=models.DateField(blank=True, null=True, verbose_name='remove from site on'),
        ),
    ]
