# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0013_auto_20170416_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news story', 'verbose_name_plural': 'news stories'},
        ),
        migrations.AddField(
            model_name='news',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='front_page',
            field=models.BooleanField(default=False, verbose_name='feature on front page'),
        ),
    ]
