# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0014_auto_20170416_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='slug', verbose_name='slug'),
            preserve_default=False,
        ),
    ]
