# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 13:13
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0016_remove_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='foo', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
