# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0017_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='extra_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='extra title text (not in link)'),
        ),
    ]
