# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0018_news_extra_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='redirect_to',
            field=models.URLField(blank=True, null=True, verbose_name='redirection story - where to go?'),
        ),
    ]
