# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0019_news_redirect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='story',
            field=models.TextField(blank=True, null=True, verbose_name='story'),
        ),
    ]
