# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0021_tdbleaderboard_entry_tdbstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdbleaderboard_entry',
            name='athlete_name',
            field=models.CharField(default='Bob', max_length=300, verbose_name='Athlete Name'),
            preserve_default=False,
        ),
    ]
