# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0022_tdbleaderboard_entry_athlete_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tdbleaderboard_entry',
            options={'verbose_name': 'TdB Leaderboard Entry', 'verbose_name_plural': 'TdB Leaderboard Entries'},
        ),
        migrations.AlterModelOptions(
            name='tdbstage',
            options={'verbose_name': 'TdB Stage', 'verbose_name_plural': 'TdB Stages'},
        ),
        migrations.AddField(
            model_name='velovolunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='velovolunteer',
            name='name',
            field=models.CharField(blank=True, help_text='Your name', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='velovolunteer',
            name='bullet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bullets.Bullet'),
        ),
    ]
