# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-23 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0023_auto_20170518_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdbstage',
            name='long_segment',
        ),
        migrations.RemoveField(
            model_name='tdbstage',
            name='medium_segment',
        ),
        migrations.RemoveField(
            model_name='tdbstage',
            name='short_segment',
        ),
        migrations.RemoveField(
            model_name='tdbstage',
            name='social_segment',
        ),
        migrations.AddField(
            model_name='tdbstage',
            name='long_route',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Long route ID'),
        ),
        migrations.AddField(
            model_name='tdbstage',
            name='medium_route',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Medium route ID'),
        ),
        migrations.AddField(
            model_name='tdbstage',
            name='short_route',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Short route ID'),
        ),
        migrations.AddField(
            model_name='tdbstage',
            name='social_route',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Social route ID'),
        ),
    ]
