# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-24 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0024_auto_20170523_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdbstage',
            name='long_distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Long distance'),
        ),
        migrations.AddField(
            model_name='tdbstage',
            name='medium_distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Medium distance'),
        ),
        migrations.AddField(
            model_name='tdbstage',
            name='short_distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Short distance'),
        ),
        migrations.AddField(
            model_name='tdbstage',
            name='social_distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Social distance'),
        ),
    ]
