# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-25 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0025_auto_20170524_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdbstage',
            name='stage_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stage type'),
        ),
    ]
