# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0026_tdbstage_stage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTSVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Vehicle Number')),
                ('name', models.CharField(max_length=300, verbose_name='Vehicle Name')),
            ],
        ),
        migrations.CreateModel(
            name='CTSVehiclePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Time Stamp')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bullets.CTSVehicle')),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
    ]
