# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0027_ctsvehicle_ctsvehicleposition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctsvehicle',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='tdbleaderboard_entry',
            name='activity_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Activity ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdbstage',
            name='overall_segment',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Overall segment ID'),
        ),
    ]
