# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-11 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0028_auto_20170529_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTSRider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Athlete Name')),
            ],
        ),
        migrations.CreateModel(
            name='CTSRiderPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_from_start', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Distance from start')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bullets.CTSRider')),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
    ]
