# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-27 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0029_ctsrider_ctsriderposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdbstage',
            name='ss_flat_segment',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Super Social flat segment ID'),
        ),
        migrations.AddField(
            model_name='tdbstage',
            name='ss_hilly_segment',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Super Social hilly segment ID'),
        ),
    ]
