# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-13 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0030_auto_20170627_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletsrunner',
            name='paid_offline',
            field=models.BooleanField(default=False, verbose_name='paid offline'),
        ),
    ]
