# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-12 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0032_velovolunteer_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterclubRider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name', max_length=200, verbose_name='name')),
                ('email', models.EmailField(max_length=200, verbose_name='email address')),
                ('club', models.CharField(choices=[('birc', 'Birchfield'), ('bull', 'Boldmere Bullets'), ('ctc', 'CTC'), ('giro', 'GIRO'), ('gori', 'Gorilla Coffee Cycling'), ('mose', 'Moseley Missiles'), ('bob', 'Pathfinders / Brothers on Bikes'), ('tamw', 'Tamworth Cycling Club')], default='birc', help_text='Which club do you normal ride with?', max_length=4, verbose_name='club')),
                ('ice', models.CharField(blank=True, help_text='Emergency Contact Number', max_length=200, verbose_name='emergency contact number')),
                ('speed', models.CharField(choices=[('les', '10/11/12mph average route about 20 miles'), ('soc', '13/14mph average speed route about 30 miles'), ('med', '15/16/17mph average speed route about 45 miles'), ('fas', '18/19/20+mph average speed route about 51 miles')], default='les', max_length=3)),
                ('signed_up', models.DateField(auto_now_add=True, verbose_name='date signed up')),
            ],
        ),
    ]
