# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-13 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0034_auto_20170813_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interclubrider',
            name='speed',
            field=models.CharField(choices=[('les', 'Lesiure (10/11/12mph - 19 miles)'), ('soc', 'Social (13/14mph - 30 miles'), ('med', 'Medium (15/16/17mph - 39 miles)'), ('fas', 'Long (18/19/20+mph - 45 miles)')], default='les', max_length=3),
        ),
    ]
