# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0035_auto_20170813_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interclubrider',
            name='club',
            field=models.CharField(choices=[('birc', 'Birchfield'), ('bull', 'Boldmere Bullets'), ('ctc', 'CTC'), ('dyna', 'Dynamic Rides'), ('giro', 'GIRO'), ('grbr', 'Great Barr and Rrdingtion Cycling Club'), ('gori', 'Gorilla Coffee Cycling'), ('mose', 'Moseley Missiles'), ('bob', 'Pathfinders / Brothers on Bikes'), ('tamw', 'Tamworth Cycling Club')], default='birc', help_text='Which club do you normal ride with?', max_length=4, verbose_name='club'),
        ),
    ]
