# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-04 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0038_auto_20170814_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interclubrider',
            name='club',
            field=models.CharField(choices=[('birc', 'Birchfield'), ('brum', 'Birmingham Easy Riders'), ('bull', 'Boldmere Bullets'), ('brez', 'Breeze Riders'), ('bob', 'Brothers on Bikes'), ('ctc', 'CTC'), ('dyna', 'Dynamic Rides'), ('giro', 'GIRO'), ('gori', 'Gorilla Coffee Cycling'), ('grbr', 'Great Barr and Erdingtion Cycling Club'), ('mose', 'Moseley Missiles'), ('path', 'Pathfinders'), ('tamw', 'Tamworth Cycling Club'), ('tmcc', 'Tamworth RMCC'), ('tita', 'Tamworth Titans')], default='birc', help_text='Which club do you normally ride with?', max_length=4, verbose_name='club'),
        ),
    ]
