# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-11 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0041_auto_20170905_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletsrunner',
            name='had_email',
            field=models.BooleanField(default=False, verbose_name='received email'),
        ),
    ]
