# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-17 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0042_bulletsrunner_had_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletRunnerPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Photo URL')),
                ('runner_number', models.PositiveSmallIntegerField(verbose_name='Runner Number')),
            ],
        ),
        migrations.AddField(
            model_name='bulletsrunner',
            name='chip_time',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chip Time'),
        ),
        migrations.AddField(
            model_name='bulletsrunner',
            name='gun_time',
            field=models.CharField(blank=True, max_length=200, verbose_name='Gun Time'),
        ),
        migrations.AddField(
            model_name='bulletsrunner',
            name='runner_number',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Runner Number'),
        ),
    ]
