# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-17 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0043_auto_20170917_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletrunnerphoto',
            name='runner_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Runner Number'),
        ),
    ]
