# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-20 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0045_bulletsrunner_had_final_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Run Date')),
                ('session_type', models.CharField(blank=True, max_length=200, verbose_name='Session type')),
                ('session_details', models.CharField(max_length=200, verbose_name='Session details')),
                ('meeting_point', models.CharField(choices=[('h', 'Harvester'), ('b', 'Boldmere Gate'), ('r', 'Blackroot Bistro')], default='h', max_length=1, verbose_name='Meeting point')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='bulletsrunner',
            name='had_email',
            field=models.BooleanField(default=False, verbose_name='received update email'),
        ),
        migrations.AlterField(
            model_name='bulletsrunner',
            name='had_final_email',
            field=models.BooleanField(default=False, verbose_name='received final email'),
        ),
    ]
