# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-23 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0046_auto_20170920_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTDBLeaderBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_id', models.PositiveIntegerField(verbose_name='Segment ID')),
                ('athlete_id', models.PositiveIntegerField(verbose_name='Athlete ID')),
                ('activity_id', models.PositiveIntegerField(verbose_name='Activity ID')),
                ('athlete_name', models.CharField(max_length=300, verbose_name='Athlete Name')),
                ('time_taken', models.DurationField(verbose_name='Time Taken')),
                ('date_completed', models.DateField(verbose_name='Date completed')),
            ],
            options={
                'verbose_name': 'NEW TdB Leaderboard Entry',
                'verbose_name_plural': 'NEW TdB Leaderboard Entries',
            },
        ),
    ]
