# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-25 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0047_newtdbleaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeloFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='email address')),
                ('name', models.CharField(blank=True, help_text='Your name', max_length=200, verbose_name='name')),
                ('volunteer_type', models.CharField(choices=[('dm', 'Domestique'), ('sd', 'Sweep Driver'), ('sn', 'Sweep Navigator'), ('fs', 'Feed Station')], default='dm', max_length=2, verbose_name='What was your volunteering role?')),
                ('question_one', models.TextField(blank=True, help_text='Tell us three things that you thought went particularly well from your experience volunteering at the Velo', verbose_name='Three things that went well?')),
                ('question_two', models.TextField(blank=True, help_text='Tell us a few things that we could have improved to make your volunteering experience even better', verbose_name='Three things we could improve?')),
                ('support_again', models.BooleanField(help_text='If the opportunity arises, do you think that the Boldmere Bullets should volunteer to support the Velo in 2018?', verbose_name='Should the Bullets support the Velo in 2018?')),
                ('volunteer_again', models.BooleanField(help_text='If we are involved in the Velo 2018, would you be willing to assist again in some role?', verbose_name='Would you volunteer to help again?')),
                ('question_three', models.TextField(help_text='What should we tell new volunteers in the future?', verbose_name='What information or advice would have been useful?')),
                ('question_four', models.TextField(help_text='Any other feedback?', verbose_name='Final thoughts?')),
            ],
        ),
    ]
