# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-25 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0048_velofeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='velovolunteer',
            name='feedback_received',
            field=models.BooleanField(default=False, verbose_name='recieved feedback'),
        ),
        migrations.AlterField(
            model_name='velofeedback',
            name='email',
            field=models.EmailField(blank=True, help_text='(you can leave this blank)', max_length=200, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='velofeedback',
            name='name',
            field=models.CharField(blank=True, help_text='(you can leave this blank)', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='velofeedback',
            name='question_four',
            field=models.TextField(blank=True, help_text='Any other feedback?', verbose_name='Final thoughts?'),
        ),
        migrations.AlterField(
            model_name='velofeedback',
            name='question_three',
            field=models.TextField(blank=True, help_text='What should we tell new volunteers in the future?', verbose_name='What information or advice would have been useful?'),
        ),
    ]
