# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-25 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0049_auto_20170925_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='velofeedback',
            name='question_four',
            field=models.TextField(blank=True, verbose_name='Final thoughts?'),
        ),
        migrations.AlterField(
            model_name='velofeedback',
            name='question_three',
            field=models.TextField(blank=True, verbose_name='What information or advice would have been useful?'),
        ),
        migrations.AlterField(
            model_name='velofeedback',
            name='volunteer_type',
            field=models.CharField(choices=[('dm', 'Domestique (on the bike)'), ('sd', 'Sweep driver'), ('sn', 'Sweep navigator'), ('fs', 'Feed station helper')], default='dm', max_length=2, verbose_name='What was your volunteering role?'),
        ),
    ]
