# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-30 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0050_auto_20170925_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtdbleaderboard',
            name='stage_type',
            field=models.CharField(choices=[('h', 'hilly'), ('f', 'flat'), ('?', 'other'), ('p', 'prologue')], default='p', max_length=1, verbose_name='Stage Type'),
        ),
    ]
