# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-02 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0051_newtdbleaderboard_stage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletsRunFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='(you can leave this blank)', max_length=200, verbose_name='name')),
                ('email', models.EmailField(blank=True, help_text='(you can leave this blank)', max_length=200, verbose_name='email address')),
                ('question_one', models.TextField(blank=True, help_text='Tell us three things that you thought went particularly well from your experience at the Bullets Run', verbose_name='Three things that went well?')),
                ('question_two', models.TextField(blank=True, help_text='Tell us a few things that we could have improved to make your Bullets Run experience even better', verbose_name='Three things we could improve?')),
                ('run_again', models.BooleanField(help_text='Do you think the Bullets should arrange another charity run in 2018?', verbose_name='Should the Bullets have another charity run in 2018?')),
                ('question_three', models.TextField(blank=True, verbose_name='Final thoughts?')),
            ],
        ),
    ]
