# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-02 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0052_bulletsrunfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletsrunfeedback',
            name='run_again',
            field=models.BooleanField(verbose_name='Should the Bullets have another charity run in 2018?'),
        ),
    ]
