# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-24 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0053_auto_20171002_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityOfYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('link', models.URLField(verbose_name='link to charity')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='vote count')),
            ],
        ),
        migrations.AddField(
            model_name='bullet',
            name='voting_ref',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, verbose_name='random uuid for voting'),
        ),
    ]
