# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-24 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0054_auto_20171024_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='voting_ref',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='random uuid for voting'),
        ),
    ]
