# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-24 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0055_auto_20171024_2148'),
    ]

    operations = [
        migrations.RenameModel('bullet', 'oldbullet'),
        migrations.DeleteModel(
            name='BulletRunnerPhoto',
        ),
        migrations.DeleteModel(
            name='BulletsRunFeedback',
        ), 
        migrations.DeleteModel(
            name='CharityOfYear',
        ),
        migrations.DeleteModel(
            name='InterclubRider',
        ),
        migrations.DeleteModel(
            name='NewTDBLeaderBoard',
        ),
        migrations.DeleteModel(
            name='TdBLeaderBoard_Entry',
        ),
        migrations.DeleteModel(
            name='TdBStage',
        ),
        migrations.DeleteModel(
            name='VeloFeedback',
        ),
        migrations.DeleteModel(
            name='BulletsRunner',
        ),
        migrations.DeleteModel(
            name='CTSRider',
        ),
        migrations.DeleteModel(
            name='CTSRiderPosition',
        ),
        migrations.DeleteModel(
            name='CTSVehicle',
        ),
        migrations.DeleteModel(
            name='CTSVehiclePosition',
        ),
        migrations.DeleteModel(
           name='VeloVolunteer',
        ),
        migrations.DeleteModel(
            name='SiteValue',
        ),

    ]

