# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-24 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0055_auto_20171024_2148'),
    ]

    operations = [
        migrations.RenameModel('bullet', 'oldbullet')
    ]

