# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 21:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0056_rename_bullets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email', models.EmailField(max_length=200, verbose_name='email address')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('email_checked', models.DateField(blank=True, null=True, verbose_name='date email confirmed')),
                ('email_check_ref', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='random uuid for email confirmation')),
                ('postcode', models.CharField(max_length=5, verbose_name='first part of postcode')),
                ('contact_no', models.CharField(max_length=100, verbose_name='contact number')),
                ('over_18', models.BooleanField(help_text='Please confirm that you are over 18?', verbose_name='over 18')),
                ('get_emails', models.BooleanField(help_text='Can we contact you regarding Collective events?', verbose_name='happy to receive emails')),
                ('voting_ref', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='random uuid for voting')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulletEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Event Name')),
                ('link', models.URLField(blank=True, help_text='If you put a web address in here then we add a link to the events page', null=True, verbose_name='Link to more info')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='display_after',
            field=models.DateField(default=datetime.date.today, verbose_name='publish on'),
        ),
        migrations.AlterField(
            model_name='news',
            name='redirect_to',
            field=models.URLField(blank=True, help_text="If you put a website address in here, then don't include a story below; the news story will just redirect to this link", null=True, verbose_name='redirection story - where to go?'),
        ),
    ]
