# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0057_auto_20180108_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='IWDRider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email', models.EmailField(max_length=200, verbose_name='email address')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('email_checked', models.DateField(blank=True, null=True, verbose_name='date email confirmed')),
                ('email_check_ref', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='random uuid for email confirmation')),
                ('club', models.CharField(blank=True, max_length=200, verbose_name='Usual club')),
                ('evans', models.BooleanField(default=True, help_text="Check this box if you'd like to take part in the bike maintenance event at Evans", verbose_name='Evans Event?')),
                ('speed', models.CharField(choices=[('n', 'I do not wish to take part in the ride'), ('a', '10-11mph'), ('b', '12-13mph'), ('c', '14-15mph'), ('d', '16-17mph'), ('e', '18+mph')], default='n', help_text='What speed would you like to do the ride at?', max_length=1, verbose_name="Women's Ride?")),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
