# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0057_auto_20180108_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='velovolunteer',
            name='bullet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bullets.OldBullet'),
        ),
    ]
