# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0058_iwdrider'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletevent',
            name='cycling_event',
            field=models.BooleanField(default=False, verbose_name='Cycling Event'),
        ),
        migrations.AddField(
            model_name='bulletevent',
            name='running_event',
            field=models.BooleanField(default=False, verbose_name='Running Event'),
        ),
        migrations.AddField(
            model_name='bulletevent',
            name='social_event',
            field=models.BooleanField(default=False, verbose_name='Social Event'),
        ),
    ]
