# Generated by Django 2.0.5 on 2018-07-03 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0059_auto_20180120_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigBulletRider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email', models.EmailField(max_length=200, verbose_name='email address')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('email_checked', models.DateField(blank=True, null=True, verbose_name='date email confirmed')),
                ('email_check_ref', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='random uuid for email confirmation')),
                ('access_token', models.CharField(max_length=500, verbose_name='Strava access token')),
                ('distance', models.CharField(choices=[('s', '50km'), ('m', '100km'), ('l', '150km'), ('v', '200km')], default='s', help_text='Please indicate which distance you would like to ride - you can change on the day!', max_length=1, verbose_name='Which distance would you like to ride?')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
