# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0060_auto_20180110_2008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteValue',
        ),
        migrations.AlterField(
            model_name='velovolunteer',
            name='bullet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bullets.OldBullet'),
        ),
    ]
