# Generated by Django 2.0.5 on 2018-07-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0060_bigbulletrider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigbulletrider',
            name='distance',
            field=models.CharField(choices=[('r', '5mile run'), ('t', '10mile run'), ('s', '50km ride'), ('m', '100km ride'), ('l', '160km ride'), ('v', '200km ride')], default='r', help_text='Please indicate which event you would like to do - you can change on the day!', max_length=1, verbose_name='Event'),
        ),
    ]
