# Generated by Django 2.0.5 on 2018-07-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0061_auto_20180710_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fredhighleaderboard',
            options={'ordering': ['-elevation']},
        ),
        migrations.AlterModelOptions(
            name='fredlowleaderboard',
            options={'ordering': ['ratio']},
        ),
        migrations.AddField(
            model_name='fredrider',
            name='checked_upto_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Checked up to'),
        ),
    ]
