# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0061_auto_20180111_2200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulletRunnerPhoto',
        ),
        migrations.DeleteModel(
            name='BulletsRunFeedback',
        ), 
        migrations.DeleteModel(
            name='CharityOfYear',
        ),
        migrations.DeleteModel(
            name='InterclubRider',
        ),
        migrations.DeleteModel(
            name='NewTDBLeaderBoard',
        ),
        migrations.DeleteModel(
            name='TdBLeaderBoard_Entry',
        ),
        migrations.DeleteModel(
            name='TdBStage',
        ),
        migrations.DeleteModel(
            name='VeloFeedback',
        ),
        migrations.DeleteModel(
            name='BulletsRunner',
        ),
        migrations.DeleteModel(
            name='CTSRider',
        ),
        migrations.DeleteModel(
            name='CTSRiderPosition',
        ),
        migrations.DeleteModel(
            name='CTSVehicle',
        ),
        migrations.DeleteModel(
            name='CTSVehiclePosition',
        ),
     #   migrations.DeleteModel(
      #      name='VeloVolunteer',
       # ),
    ]
