# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0062_auto_20180112_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Event Name')),
                ('link', models.URLField(blank=True, help_text='If you put a web address in here then we add a link to the events page', null=True, verbose_name='Link to more info')),
            ],
        ),
    ]
