# Generated by Django 2.0.5 on 2018-08-02 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0062_auto_20180728_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquareRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.CharField(max_length=20, verbose_name='Strava Activity ID')),
                ('name', models.CharField(max_length=500, verbose_name='Ride Name')),
                ('polyline', models.TextField(verbose_name='Polyline')),
            ],
        ),
        migrations.CreateModel(
            name='SquareRider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_id', models.CharField(max_length=20, verbose_name='Strava Rider ID')),
                ('access_token', models.CharField(max_length=500, verbose_name='Strava access token')),
            ],
        ),
        migrations.AddField(
            model_name='squareride',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bullets.SquareRider'),
        ),
    ]
