# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0063_auto_20180113_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='IWDRider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email', models.EmailField(max_length=200, verbose_name='email address')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('email_checked', models.DateField(blank=True, null=True, verbose_name='date email confirmed')),
                ('email_check_ref', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='random uuid for email confirmation')),
                ('club', models.CharField(blank=True, max_length=200, verbose_name='Usual club')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ), 
    ]
