# Generated by Django 2.0.5 on 2018-09-11 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0063_auto_20180802_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigBulletRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Strava ID')),
                ('distance', models.PositiveIntegerField(verbose_name='Distance')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Activity Date')),
                ('bullet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bullets.BigBulletRider')),
            ],
        ),
    ]
