# Generated by Django 2.0.5 on 2018-09-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0064_bigbulletride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigbulletride',
            name='bullet',
        ),
        migrations.RemoveField(
            model_name='activitycache',
            name='activity_id',
        ),
        migrations.DeleteModel(
            name='BigBulletRide',
        ),
    ]
