# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0064_auto_20180114_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='iwdrider',
            name='event',
            field=models.CharField(choices=[('e', 'Bike maintenance evening ONLY'), ('r', 'Saturday bike ride ONLY'), ('b', 'Take part in both events')], default='b', max_length=1, verbose_name='Which event?'),
        ),

    ]
