# Generated by Django 2.0.5 on 2018-09-13 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0065_auto_20180913_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitycache',
            name='start_date',
        ),
        migrations.AddField(
            model_name='activitycache',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Activity Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitycache',
            name='name',
            field=models.CharField(default='Default Activity', max_length=1000, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
