# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0065_auto_20180115_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iwdrider',
            name='event',
        ),
        migrations.AddField(
            model_name='iwdrider',
            name='evans',
            field=models.BooleanField(default=True, help_text='Would you like to take part in the bike maintenance event at Evans?', verbose_name='Evans Event?'),
        ),
        migrations.AddField(
            model_name='iwdrider',
            name='speed',
            field=models.CharField(choices=[('n', 'I do not wish to take part in the ride'), ('a', '10-11mph'), ('b', '12-13mph'), ('c', '14-15mph'), ('d', '16-17mph'), ('e', '18+mph')], default='n', help_text='What speed would you like to do the ride at?', max_length=1, verbose_name="Women's Ride?"),
        ),

    ]
