# Generated by Django 2.0.5 on 2018-09-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullets', '0066_auto_20180913_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycache',
            name='athlete',
            field=models.CharField(default='Nobody', max_length=1000, verbose_name='Athlete'),
            preserve_default=False,
        ),
    ]
