# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20170720_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='language_code',
            field=models.CharField(default='en-gb', max_length=35),
        ),
    ]
