# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20170720_1948'),
        ('order', '0026_auto_20171218_0428'),
    ]

    operations = [
    ]
