# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_merge_20171228_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='language_code',
            field=models.CharField(default='en-us', max_length=35),
        ),
    ]
