# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20180103_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='future_shipping',
            field=models.BooleanField(default=False, verbose_name='future shipping'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=django_prices.models.PriceField(blank=True, currency='GBP', decimal_places=2, max_digits=12, null=True, verbose_name='discount amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='language_code',
            field=models.CharField(default='en-GB', max_length=35),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_price',
            field=django_prices.models.PriceField(currency='GBP', decimal_places=4, default=0, editable=False, max_digits=12, verbose_name='shipping price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_net',
            field=django_prices.models.PriceField(blank=True, currency='GBP', decimal_places=2, max_digits=12, null=True, verbose_name='total net'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_tax',
            field=django_prices.models.PriceField(blank=True, currency='GBP', decimal_places=2, max_digits=12, null=True, verbose_name='total tax'),
        ),
    ]
