# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_merge_20180103_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='future_shipping',
            field=models.BooleanField(default=False, verbose_name='future shipping'),
        ),
    ]
