# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_auto_20180119_0405'),
        ('order', '0028_auto_20180103_2338'),
    ]

    operations = [
    ]
