# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_merge_20180124_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernote',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
