# Generated by Django 2.0.2 on 2018-03-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_auto_20180123_0832'),
        ('order', '0033_auto_20180124_2324'),
    ]

    operations = [
    ]
