# Generated by Django 2.0.2 on 2018-03-03 14:44

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_merge_20180303_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=django_prices.models.PriceField(blank=True, currency='GBP', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_price',
            field=django_prices.models.PriceField(currency='GBP', decimal_places=4, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_net',
            field=django_prices.models.PriceField(blank=True, currency='GBP', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_tax',
            field=django_prices.models.PriceField(blank=True, currency='GBP', decimal_places=2, max_digits=12, null=True),
        ),
    ]
