# Generated by Django 2.0.5 on 2018-05-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_order_line_name_length'),
        ('order', '0034_merge_20180303_1438'),
    ]

    operations = [
    ]
